# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
      uses: actions/checkout@master
    - name: create key secret file
      run: 'echo $SECRET_KEY > secret.txt'
      shell: bash
      env:
          SECRET_KEY: ${{ secrets.USERNAME }}
    - name: send to host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "secret.txt"
        target: "/root/bots/"
      
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: scp copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "tests/*"
        target: "/root/bots/"

